"""initial schema

Revision ID: 07a9d9758312
Revises: 
Create Date: 2026-03-15 15:53:01.617993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07a9d9758312'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('police_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('cpf', sa.String(length=20), nullable=True),
    sa.Column('plan', sa.String(length=50), nullable=True),
    sa.Column('max_dashboards', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('police_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_police_users_email'), ['email'], unique=True)

    op.create_table('access_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('accessed_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['police_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dashboard_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['police_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intake_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dashboard_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('form_schema', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboard_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('minimal_log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dashboard_id', sa.Integer(), nullable=False),
    sa.Column('police_user_id', sa.Integer(), nullable=False),
    sa.Column('guest_display_name', sa.String(length=200), nullable=True),
    sa.Column('crime_type', sa.String(length=100), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboard_sessions.id'], ),
    sa.ForeignKeyConstraint(['police_user_id'], ['police_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('minimal_log_entries')
    op.drop_table('intake_links')
    op.drop_table('dashboard_sessions')
    op.drop_table('access_logs')
    with op.batch_alter_table('police_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_police_users_email'))

    op.drop_table('police_users')
    # ### end Alembic commands ###
