"""add_plans_sessions_and_sms

Revision ID: 265f95c93217
Revises: 07a9d9758312
Create Date: 2026-03-30 01:18:20.661944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '265f95c93217'
down_revision = '07a9d9758312'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_sms_counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month')
    )
    op.create_table('sms_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sms_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sms_verifications_phone'), ['phone'], unique=False)

    op.create_table('plan_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('sessions_created', sa.Integer(), nullable=True),
    sa.Column('total_submissions', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['police_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'month', name='uq_plan_usage_user_month')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['police_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    with op.batch_alter_table('police_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('plan_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('trial_ends_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('plan_usage_reset_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('police_users', schema=None) as batch_op:
        batch_op.drop_column('plan_usage_reset_at')
        batch_op.drop_column('trial_ends_at')
        batch_op.drop_column('plan_type')
        batch_op.drop_column('phone_verified_at')

    op.drop_table('user_sessions')
    op.drop_table('plan_usages')
    with op.batch_alter_table('sms_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sms_verifications_phone'))

    op.drop_table('sms_verifications')
    op.drop_table('global_sms_counters')
    # ### end Alembic commands ###
